apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 20Mi
        env:
        - name: ENVIRONMENT 
          valueFrom:
            configMapKeyRef:
              name: settings
              key: environment
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: settings
              key: version
        volumeMounts:
        - name: settings
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: settings
        configMap:
          name: settings