kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/kustomize/dev(/|$)(.*)"
        backend:
          service:
            name: app-service
            port:
              number: 8083