apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-helm
  namespace: argocd
spec:
  description: Example with Kustomize
  destinations:
    - name: '*'
      namespace: helm
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/lehnert-andre/argo-cd-gitops-repository'
