apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-dev
  labels:
    kubernetes.io/metadata.name: kustomize-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-prod
  labels:
    kubernetes.io/metadata.name: kustomize-prod
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kustomize
  namespace: argocd
spec:
  description: Example with Kustomize
  destinations:
    - name: 'DEV'
      namespace: kustomize-dev
      server: 'https://kubernetes.default.svc'
    - name: 'PROD'
      namespace: kustomize-prod
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/lehnert-andre/argo-cd-gitops-repository'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app-dev
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kustomize-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/app/env/dev
    repoURL: 'https://github.com/lehnert-andre/argo-cd-gitops-repository.git'
    targetRevision: HEAD
  project: kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app-prod
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kustomize-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: kustomize/app/env/prod
    repoURL: 'https://github.com/lehnert-andre/argo-cd-gitops-repository.git'
    targetRevision: HEAD
  project: kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s


