apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
spec:
  destination:
    name: ''
    namespace: kustomize
    server: 'https://kubernetes.default.svc'
  source:
    path: application/kustomize/env/dev
    repoURL: 'https://github.com/lehnert-andre/argo-cd-gitops-repository.git'
    targetRevision: HEAD
  project: gitops-kustomize
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
